"""
Core Logic: Standard switches and routers are entirely stateless when it comes to ARP. 
If an interface receives an ARP Reply, it blindly updates its MAC table or ARP cache, 
which is exactly why ARP Cache Poisoning (Module 04E) is so devastating.

When Next-Generation Firewalls (NGFWs like Palo Alto or Fortinet) are deployed in 
Layer 2 Transparent Mode ("Bump-in-the-Wire"), they apply Stateful Deep Packet 
Inspection (DPI) to Layer 2 protocols.

The Stateful ARP Engine:
1. The Firewall maintains a strict state table of all pending ARP Requests.
2. When Host A asks for Host B, the firewall records: [Transaction ID, Src IP, Dst IP].
3. If an ARP Reply arrives at the firewall, DPI rips open the packet and inspects 
   the Layer 2.5 payload.
4. It verifies the Reply against the pending state table. If there was no matching 
   prior Request, the packet is flagged as an unsolicited injection (Spoofing) and dropped.
5. Furthermore, DPI ensures the Sender MAC in the ARP payload strictly matches the 
   Source MAC in the Ethernet header. If a tool like Scapy was used to forge the 
   payload MAC but the NIC sent a different hardware MAC, the firewall instantly 
   shreds the frame.
"""

import sys
import shutil
import time
from typing import Any, Dict

class StatefulARPFirewallEngine:
    fw_state: Dict[str, Any]

    def __init__(self) -> None:
        self.fw_state = {}
        
        # Firewall State Tables
        self.pending_arp_requests = set()
        self.established_l2_bindings = {
            "10.0.0.1": "GW:00:11:22:33:44" # Known immutable gateway
        }
        
    def get_terminal_width(self) -> int:
        return min(shutil.get_terminal_size().columns, 115)

    def execute_dpi_inspection(self, scenario: str) -> None:
        """Simulates Deep Packet Inspection on Layer 2 ARP frames across security zones."""
        
        flow = []
        frames = []
        action = ""
        insight = ""
        
        flow.append("1. [Dataplane]: Frame arrives on Firewall Ingress Interface (Zone: Trust).")
        flow.append("2. [DPI Engine]: Stripping L2 header. Extracting raw ARP payload.")
        
        if scenario == "1":
            # Legitimate Request-Reply Cycle
            flow.append("3. [Host 10.0.0.50]: Broadcasts ARP Request -> 'Who has 10.0.0.75?'")
            self.pending_arp_requests.add("10.0.0.50->10.0.0.75")
            flow.append("4. [Stateful Engine]: Request logged. State created. Frame permitted.")
            
            flow.append("\n   --- 2 milliseconds later ---")
            flow.append("5. [Host 10.0.0.75]: Unicasts ARP Reply -> '10.0.0.75 is at AA:BB:CC:75:75:75'.")
            flow.append("6. [DPI Engine]: Verifying Reply against State Table.")
            
            if "10.0.0.50->10.0.0.75" in self.pending_arp_requests:
                flow.append("7. [Stateful Engine]: MATCH FOUND. Transaction validated.")
                self.established_l2_bindings["10.0.0.75"] = "AA:BB:CC:75:75:75"
                self.pending_arp_requests.remove("10.0.0.50->10.0.0.75")
                action = "PERMIT (State Validated)"
                insight = "The firewall treats ARP just like TCP. No reply is allowed through the firewall unless the corresponding request was observed and tracked. True stateful inspection at Layer 2."
                
                frame = {
                    "type": "ARP Reply (Legitimate)",
                    "payload": "Sender IP: 10.0.0.75 | Target IP: 10.0.0.50",
                    "state_match": "YES (Request observed in session table)"
                }
                frames.append(frame)

        elif scenario == "2":
            # Unsolicited Poisoning (MitM Attack)
            flow.append("3. [Attacker 10.0.0.99]: Injects unsolicited ARP Reply -> '10.0.0.1 (Gateway) is at AT:TA:CK:99:99:99'.")
            flow.append("4. [DPI Engine]: Verifying Reply against State Table.")
            flow.append("5. [Stateful Engine]: MISS. No pending request for 10.0.0.1 was ever generated by the subnet.")
            flow.append("6. [DPI Engine]: Checking Established Bindings.")
            flow.append(f"7. [Stateful Engine]: CONFLICT. 10.0.0.1 is strictly bound to {self.established_l2_bindings['10.0.0.1']}.")
            flow.append("8. [Security Policy]: Threat detected. Frame instantly dropped. Alert generated.")
            
            action = "DROP (Unsolicited / Poison Attempt)"
            insight = "Because the firewall did not observe a host requesting the Gateway's MAC, it knows the reply is an unsolicited injection designed to poison caches. The attacker's frame never reaches the victim's switchport."
            
            frame = {
                "type": "ARP Reply (Forged)",
                "payload": "Sender IP: 10.0.0.1 (Spoofed) | Target IP: 10.0.0.50",
                "state_match": "NO (Orphaned Reply)"
            }
            frames.append(frame)

        elif scenario == "3":
            # Header vs Payload Mismatch (Scapy Manipulation)
            flow.append("3. [Attacker]: Crafts malformed ARP packet via Python Scapy.")
            flow.append("4. [DPI Engine]: Executing Header-to-Payload consistency check.")
            flow.append("5. [DPI Engine]: Ethernet Src MAC  -> DE:AD:BE:EF:00:00")
            flow.append("6. [DPI Engine]: ARP Payload MAC -> GW:00:11:22:33:44 (Gateway MAC)")
            flow.append("7. [Stateful Engine]: MAC MISMATCH. The physical sender is lying about their payload identity.")
            flow.append("8. [Security Policy]: Protocol violation detected. Frame shredded.")
            
            action = "DROP (Protocol Anomaly - MAC Mismatch)"
            insight = "DPI does not just look at IPs. It cross-references the Layer 2 Ethernet headers with the Layer 2.5 ARP payload. If a tool forges the payload to claim ownership of an IP, but the physical NIC MAC doesn't match the payload MAC, the firewall catches the lie."
            
            frame = {
                "type": "ARP Request/Reply (Malformed)",
                "payload": "Ethernet Src: DE:AD:BE:EF:00:00 != ARP Sender MAC: GW:00:11:22:33:44",
                "state_match": "N/A (Failed Integrity Check)"
            }
            frames.append(frame)

        self.fw_state = {
            "scenario": scenario,
            "flow": flow,
            "frames": frames,
            "action": action,
            "insight": insight
        }

    def render_ui(self) -> None:
        time.sleep(0.3)
        width = self.get_terminal_width()
        state = self.fw_state
        
        print("\n" + "=" * width)
        print(" [>] MODULE 04AR: STATEFUL ARP FIREWALL & DPI ENGINE ".center(width))
        print("=" * width)
        
        print(" [+] FIREWALL STATE TABLES (ZONE: TRUST):")
        print(f"     -> Pending Requests : {list(self.pending_arp_requests) if self.pending_arp_requests else 'None'}")
        print(f"     -> L2 Bindings      : {self.established_l2_bindings}")
        print("-" * width)
        
        print(" [i] DPI INSPECTION SEQUENCE:")
        for step in state['flow']:
            time.sleep(0.2)
            print(f"     {step}")
        print("-" * width)
        
        if state['frames']:
            print(" [!] DATAPLANE FRAME ANALYSIS:")
            time.sleep(0.3)
            for frame in state['frames']:
                print(f"\n     [Frame Profile: {frame['type']}]")
                print(f"     -> Payload Integrity : {frame['payload']}")
                print(f"     -> Stateful Session  : {frame['state_match']}")
                time.sleep(0.4)
        
        print("\n" + "-" * width)
        print(f"     -> Security Action  : [ {state['action']} ]")
        print(f" [!] ARCHITECTURAL ENGINEERING INSIGHT:")
        print(f"     -> {state['insight']}")
        print("=" * width + "\n")


def interactive_loop() -> None:
    engine = StatefulARPFirewallEngine()
    width = engine.get_terminal_width()
    
    print("\n" + "=" * width)
    print(" 04AR_STATEFUL_ARP_TRACKING INITIALIZED ".center(width))
    print(" Type 'quit' or press Ctrl+C to safely shut down.".center(width))
    print("=" * width)

    while True:
        try:
            print("\n[?] Select L2 Firewall Inspection Scenario:")
            print("    1. Legitimate Request-Reply (Stateful Session Creation)")
            print("    2. Unsolicited ARP Reply (Cache Poisoning / MitM Attempt)")
            print("    3. Scapy Header/Payload Mismatch (Protocol Anomaly)")
            
            choice = input("    Select scenario (1/2/3) [Default: 1] : ").strip() or "1"
            if choice.lower() in ['quit', 'exit']: sys.exit(0)
            
            if choice not in ["1", "2", "3"]:
                raise ValueError("Selection Error: Please choose 1, 2, or 3.")
            
            engine.execute_dpi_inspection(choice)
            engine.render_ui()
            
        except ValueError as ve:
            print(f"\n[X] INTERCEPT TRIGGERED:\n    {ve}")
        except KeyboardInterrupt:
            print("\n\n[!] Interrupt signal received. Shutting down...")
            sys.exit(0)
        except Exception as e:
            print(f"\n[X] CRITICAL SYSTEM FAULT: {e}")

if __name__ == "__main__":
    interactive_loop()